# colors with alpha channel
library(grDevices)
gray_transparent <- adjustcolor("gray50", alpha.f=0.6)
gray_lighter <- adjustcolor("gray92", alpha.f=1)
gray_light <- adjustcolor("gray88", alpha.f=1)
gray_selected <- adjustcolor("gray80", alpha.f=1)
gray_dark <- adjustcolor("gray50", alpha.f=1)
gray_darker <- adjustcolor("gray30", alpha.f=1)
blue_light <- adjustcolor("skyblue1", alpha.f=1)
blue_dark <- adjustcolor("steelblue4", alpha.f=1)
red_light <- adjustcolor("salmon", alpha.f=1)
red_dark <- adjustcolor("firebrick3", alpha.f=1)